In [1]:
#                                          Python Tasks – Day13 
#1. Write a Python Code to count the Number of Each Vowel in a given string 
vowels = 'aeiou'

ip_str = 'Data Science is an interdisciplinary field that  uses scientific methods.'

# make it suitable for caseless comparisions
ip_str = ip_str.casefold()

# make a dictionary with each vowel a key and value 0
count = {}.fromkeys(vowels,0)

# count the vowels
for char in ip_str:
   if char in count:
       count[char] += 1

print(count)

{'a': 5, 'e': 7, 'i': 10, 'o': 1, 'u': 1}


In [2]:
#2. Write a Python Code to count number of words, characters and number of spaces in a given string 
string = input("Enter a string:");  
count = 0;  
   
#Counts each character except space  
for i in range(0, len(string)):  
    if(string[i] != ' '):  
        count = count + 1;  
   
#Displays the total number of characters present in the given string  
print("Total number of characters in a string: " + str(count));  

Enter a string:Machine Learning is a method of data analysis that automates analytical model building.
Total number of characters in a string: 75


In [3]:
#3. Write a Python Program to remove punctuation from a given string (using loop)
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

str = input("Enter a string:")



# remove punctuation from the string
no_punct = ""
for char in str:
   if char not in punctuations:
       no_punct = no_punct + char

# display the unpunctuated string
print(no_punct)

Enter a string:Hello! My name is Rana. How are you?
Hello My name is Rana How are you


In [6]:
#4.Write a Python Program to take a mxn matrix input from user and stored in nested list 
import numpy as np  
  
Rows = int(input("Give the number of rows:"))  
Columns = int(input("Give the number of columns:"))  
  
print("Please write the elements of the matrix in a single line and separated by a space: ")  
  
# User will give the entries in a single line  
elements = list(map(int, input().split()))  
  
# Printing the matrix given by the user  
matrixx = np.array(elements).reshape(Rows, Columns)  
print(matrixx)  

Give the number of rows:3
Give the number of columns:3
Please write the elements of the matrix in a single line and separated by a space: 
2 4 6 8 3 5 7 9 1
[[2 4 6]
 [8 3 5]
 [7 9 1]]


In [1]:
#5.Write a Python Program to add, multiply and transpose two matrices given by user  

print("Enter the size of two matrices of MxN order....")
m=int(input("\tM = "))
n=int(input("\tN = "))
matrix1=[]
print("Enter the entries of first matrix rowwise:")
for i in range(m):
    a=[]
    for j in range(n):
        a.append(int(input()))
    matrix1.append(a)
matrix2=[]
print("Enter the entries of second matrix rowwise:")
for i in range(m):
    a=[]
    for j in range(n):
        a.append(int(input()))
    matrix2.append(a)

print("\nMatrix-1: ")
for i in range(m):
    print("       ",end=" ")
    for j in range(n):
        print(matrix1[i][j],end=" ")
    print()
    
print("\nMatrix-2: ")
for i in range(m):
    print("       ",end=" ")
    for j in range(n):
        print(matrix2[i][j],end=" ")
    print()
    
results=[]
for i in range(m):
    a=[]
    for j in range(n):
        a.append(matrix1[i][j]+matrix2[i][j])
    results.append(a)
print("\nSum of two matrix: ")
for i in range(m):
    print("       ",end=" ")
    for j in range(n):
        print(f"{results[i][j]:>3}",end=" ")
    print()
    
resultm=[]
for i in range(len(matrix1)):
    a=[]
    for j in range(len(matrix2[0])):
        c=0
        for k in range(len(matrix2)):
            c+= matrix1[i][k] * matrix2[k][j]
        a.append(c)
    resultm.append(a)
print("\nMultiplication of two matrix: ")
for i in range(m):
    print("       ",end=" ")
    for j in range(n):
        print(f"{resultm[i][j]:>4}",end=" ")
    print()   

resultt1=[]
for i in range(m):
    a=[]
    for j in range(n):
        a.append(matrix1[j][i])
    resultt1.append(a)
resultt2=[]
for i in range(m):
    a=[]
    for j in range(n):
        a.append(matrix1[j][i])
    resultt2.append(a)
print("\nTranspose of Matrix-1: ")
for i in range(m):
    print("       ",end=" ")
    for j in range(n):
        print(f"{resultt1[i][j]:>2}",end=" ")
    print()   
print("\nTranspose of Matrix-2: ")
for i in range(m):
    print("       ",end=" ")
    for j in range(n):
        print(f"{resultt2[i][j]:>2}",end=" ")
    print()   

Enter the size of two matrices of MxN order....
	M = 2
	N = 2
Enter the entries of first matrix rowwise:
2
4
6
8
Enter the entries of second matrix rowwise:
3
5
7
9

Matrix-1: 
        2 4 
        6 8 

Matrix-2: 
        3 5 
        7 9 

Sum of two matrix: 
          5   9 
         13  17 

Multiplication of two matrix: 
          34   46 
          74  102 

Transpose of Matrix-1: 
         2  6 
         4  8 

Transpose of Matrix-2: 
         2  6 
         4  8 
